### ISSUE TITLE
Các Tweaks của HoneCtrl hiển thị chưa chính xác

### ISSUE THREAD

**Issue by DRGFL** [NamGitHub2002/OptimizedTools#3]
[HONECTRL]
**Describe the bug**
Ở phần [ 6 ] Advanced  >>  Others Tweaks, phần 9 bị mất, nên làm lẫn lộn các con số tuỳ chọn: nhập vào "10" thì nó bật tweak 11, muốn bật tweak 10 thì phải nhập "9", khá là củ chuối, mình không chắc lẫn lộn như vậy có bật đúng thứ mình cần không. btw thì nó cx thiếu mục Power plans ở phần [ 1 ] Optimizations 
**Expected behavior**
Bật đúng số tweak: nhập 10 thì bật 10, nhập 11 thì bật 11, bổ sung lại các tweak bị xoá

**Screenshots**
![image](https://github.com/NamOpt/OptimizedTools/assets/155883444/085cb58d-bcd6-4994-9732-352835867418)

**Comment by NamOpt** [comment]
Có hai lí do ở đây:
1. Đó là lỗi của phần mềm HoneCTRL. Đầu tiên thì mình muốn xin lỗi bạn về trải nghiệm không tốt của bạn. Bạn vui lòng report và tạo issues trong Github Repo của HoneCTRL: https://github.com/luke-beep/HoneCTRL/issues
2. Đối với phần Power plan: tùy phần mềm HoneCTRL nhé, cứ tạo issues ở HoneCTRL.

Nếu có gì mới, cứ nhập Comments hoặc Re-Open issues.
